### ISSUE TITLE
Settings breekt

### ISSUE THREAD

**Issue by JustxMeg** [PStokman/DarkTweakers#1]
https://tweakers.net/instellingen/layout/

Deze pagina is erg buggy met de CSS.

**Comment by PStokman** [comment]
De dropdowns en onderdelenaanduiding zijn 'stuk' omdat deze eerst keihard overruled werden met !important. Die heb ik er allemaal uit gehaald, dus er zullen wel meer pagina's zijn die niet helemaal goed eruit zien.

Dit is dus een van de zaken die een betere selector vereisen of toch met !important omheen gewerkt moet worden.

**Comment by PStokman** [comment]
Een paar selectors beter gemaakt. Pagina ziet er nu weer prima uit.
